feature/custom-tab-itens-component
loomi/loomi-ui-flutter pull request #10
Opened 2023-08-14 16:51 UTC by lucasvps

_Changes:_

_1. What i did:_

- Completed the [task](https://www.notion.so/5e06e62f649b4d5c8a2f40a85f74c771?v=14e3d2c090ca484db4b6e2f077a7347a&p=09afed8a214842cf8e63a62acf38dd2e&pm=s)
- Create a Custom Tab Item Component

_2. What to test:_

- [ ] Layout on different devices ([mockup](link_to_mockup))
- [ ] Happy path
- [ ] Error handling

---

_How to get there_

_1. Flavor and login informations_

> _flavor_: staging

_2. Steps_

- Run Example App
- Click on Example Screen Button

---

_Observations:_

_1. Known issues_

- No design to based yet

_2. Code review pratices_

- Unecessary prints/log (ctrl+f -> [ print( ] )
- Unecessary comments (ctrl+f -> [ // ] )
- Code organization
- Naming of functions and variables
- Repeated code

2023-08-17 12:57 UTC, gabrielerego123 approved these changes

2023-08-17 20:27 UTC, ItaloDias-stack requested changes

2023-08-17 20:27 UTC, ItaloDias-stack commented on example/lib/screens/example_screen.dart
> +import 'dart:developer';
Remover essa tela

2023-08-17 20:27 UTC, ItaloDias-stack commented on lib/widgets/custom_tab_items.dart
> +      // height: 40,
Remover comentário

2023-08-18 00:29 UTC, lucasvps commented on example/lib/screens/example_screen.dart
> +import 'dart:developer';
Por que exatamente remover essa tela?

2023-08-18 19:41 UTC, arkaisho requested changes

2023-08-18 19:41 UTC, arkaisho commented on example/lib/screens/example_screen.dart
> +              CustomTabItens(
```suggestion
              CustomTabItems(
```

2023-08-21 17:09 UTC, merged