Fix: media player and update libs
loomi/loomi-ui-flutter pull request #13
Opened 2023-10-02 13:58 UTC by ItaloDias-stack

_Changes:_

_1. What i did:_

- I've fixed the media player and update some libs

_2. What to test:_

- [ ] Test in different projects

---

_1. Steps_

- Put this lib in some projects

---

_Observations:_

_1. Code review pratices_

- Unecessary prints/log (ctrl+f -> [ print( ] )
- Unecessary comments (ctrl+f -> [ // ] )
- Code organization
- Naming of functions and variables
- Repeated code

2023-10-02 14:04 UTC, arkaisho requested changes

2023-10-02 14:04 UTC, arkaisho commented on lib/widgets/file_picker/components/file_picker_player/file_picker_player.dart
> +    // );
Remover comentário

2023-10-02 14:04 UTC, arkaisho commented on lib/widgets/file_picker/components/file_picker_player/file_picker_player.dart
> +      ..initialize().then((value) {
Adicionar parâmetro para o autoplay

2023-10-03 14:33 UTC, arkaisho approved these changes

2023-10-03 19:53 UTC, lucasvps approved these changes

2023-10-05 20:20 UTC, merged