Create custom app bar
loomi/loomi-ui-flutter pull request #9
Opened 2023-08-09 17:15 UTC by gabrielerego123

_Changes:_

_1. What i did:_

- Completed the [task](https://www.notion.so/Custom-App-Bar-721e8fd750c84489a449ac8ad930302b)
- Create custom app bar with options to widgets in right e left side.

_2. What to test:_

- [ ] Happy path
- [ ] Error handling

---

_How to get there_

_1. Flavor and login informations_

> _flavor_: staging
>
> _login_: loomi
>
> _password_: 12345678

_2. Steps_

- Do login
---

_Observations:_

_1. Known issues_

- Put them here if there are any

_2. Code review pratices_

- Unecessary prints/log (ctrl+f -> [ print( ] )
- Unecessary comments (ctrl+f -> [ // ] )
- Code organization
- Naming of functions and variables
- Repeated code

2023-08-16 21:02 UTC, lucasvps approved these changes

2023-08-17 20:22 UTC, ItaloDias-stack requested changes

2023-08-17 20:22 UTC, ItaloDias-stack commented on lib/widgets/custom_app_bar.dart
> +                  ),
Colocar para executar o "onTapPrefix" independente do "leading"

2023-08-18 00:32 UTC, lucasvps commented on lib/widgets/custom_app_bar.dart
> +                  ),
Acho que a ideia do onTapPrefix é para funcionar justamente ao clicar no leading

2023-08-21 17:01 UTC, merged